language: elixir
dist: trusty
elixir:
  - 1.6.5
otp_release:
  - 20.3
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
