language: elixir
dist: trusty
elixir:
  - 1.4.5
otp_release:
  - 20.0
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - cp config/test.exs.travis config/test.exs
install:
  - mkdir -p priv/repo/migrations
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
