language: elixir
dist: trusty
elixir:
  - 1.8.0
otp_release:
  - 21.0
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: '9.5'
services:
  - postgresql
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis --pro
